### ISSUE TITLE
Eventstore or Marten?

### ISSUE THREAD

**Issue by paulvanbladel** [tim-cools/EventStore-Examples#2]
Tim,
Hope you don't mind asking you a question via this channel.
Would you still use today eventstore? Marten? Akka.net? Or something else?
cheers
paul.

**Comment by tim-cools** [comment]
Hey Paul, sure, no problem!
I don't use EventStore in production atm anymore. I like the product, especially the build in projections are awesome, but I prefer not to go through the hassle to host it our-self if managed services (e.g. Postgres, Mongodb) are sufficient.
I do use Marten in production for a larger web-app with event-sourcing. It isn't tested against a huge load yet, but I really like the ease of development. Postgres is also quite nice to work with and available as a managed service both on aws and azure. I also using MongoDb more lately, especially if we need high performance over multi-document transaction. But I didn't use it with event-sourcing. And I haven't played with Akka.net yet...
Cheers
Tim

**Comment by paulvanbladel** [comment]
Thanks a lot Tim. Very much appreciated.
