### ISSUE TITLE
Blog series links broken

### ISSUE THREAD

**Issue by edgarjrg** [tim-cools/EventStore-Examples#3]
Hi! The blog series links are broken.

I know those are a bit old, but do you know any other good doc/examples for EventStore? How was your experience with EventStore?

**Comment by tim-cools** [comment]
Hi! The blog is still online, I updated link so it works again ;-)

The blog post also links to a few other resources, although I havn't looked into ES recently. I think ES is a powerful database, but I don't think you need it in most software environments.
